
export const secretWords = [
  { "word": "Avión", "category": "Vehículo" },
  { "word": "Banco", "category": "Lugar" },
  { "word": "Playa", "category": "Lugar" },
  { "word": "Circo", "category": "Lugar" },
  { "word": "Hospital", "category": "Lugar" },
  { "word": "Hotel", "category": "Lugar" },
  { "word": "Biblioteca", "category": "Lugar" },
  { "word": "Cine", "category": "Lugar" },
  { "word": "Transatlántico", "category": "Vehículo" },
  { "word": "Tren de Pasajeros", "category": "Vehículo" },
  { "word": "Barco Pirata", "category": "Vehículo" },
  { "word": "Estación Polar", "category": "Lugar" },
  { "word": "Comisaría", "category": "Lugar" },
  { "word": "Restaurante", "category": "Lugar" },
  { "word": "Escuela", "category": "Lugar" },
  { "word": "Estación Espacial", "category": "Lugar" },
  { "word": "Submarino", "category": "Vehículo" },
  { "word": "Supermercado", "category": "Lugar" },
  { "word": "Universidad", "category": "Lugar" },
  { "word": "Zoológico", "category": "Lugar" },
  { "word": "Astronauta", "category": "Trabajo" },
  { "word": "Payaso", "category": "Trabajo" },
  { "word": "Detective", "category": "Trabajo" },
  { "word": "Doctor", "category": "Trabajo" },
  { "word": "Granjero", "category": "Trabajo" },
  { "word": "Bombero", "category": "Trabajo" },
  { "word": "Piloto", "category": "Trabajo" },
  { "word": "Policía", "category": "Trabajo" },
  { "word": "Científico", "category": "Trabajo" },
  { "word": "Soldado", "category": "Trabajo" },
  { "word": "Maestro", "category": "Trabajo" },
  { "word": "Guitarra", "category": "Objeto" },
  { "word": "Piano", "category": "Objeto" },
  { "word": "Televisión", "category": "Objeto" },
  { "word": "Computadora", "category": "Objeto" },
  { "word": "Pizza", "category": "Comida" },
  { "word": "Helado", "category": "Comida" },
  { "word": "Sushi", "category": "Comida" },
  { "word": "Café", "category": "Comida" },
  { "word": "León", "category": "Animal" },
  { "word": "Elefante", "category": "Animal" },
  { "word": "Tiburón", "category": "Animal" },
  { "word": "Águila", "category": "Animal" }
];